import type { PurchaseRequest } from "./types";

export const mockPRs: PurchaseRequest[] = [
  {
    id: "1",
    prNo: "PR-0012",
    createdDate: "2024-03-01T10:00:00Z",
    requester: "Turan Həsənov",
    authorId: "currentUser",
    department: "İT",
    description: "Yeni proqram təminatı lisenziyaları və avadanlıqlar.",
    totalAmount: 1250,
    status: "pending",
    category: "İT",
    costCenter: "İT Avadanlıqları",
    products: [
      { id: "p1", name: "Dell Monitor 27 inch", quantity: 2, value: 625 },
    ],
    files: [],
  },
  {
    id: "2",
    prNo: "PR-0013",
    createdDate: "2024-03-02T14:30:00Z",
    requester: "Məmməd Əliyev",
    authorId: "user2",
    department: "Təsərrüfat",
    description: "Təmizlik ləvazimatları və ofis təmiri üçün materiallar.",
    totalAmount: 450,
    status: "pending",
    category: "Təsərrüfat",
    costCenter: "Ofis Xərcləri",
    products: [{ id: "p2", name: "Təmizlik dəsti", quantity: 5, value: 90 }],
    files: [],
  },
  {
    id: "3",
    prNo: "PR-0014",
    createdDate: "2024-03-03T09:15:00Z",
    requester: "Aysel Quliyeva",
    authorId: "user3",
    department: "HR",
    description: "Yeni işçilər üçün ofis ləvazimatı - kağız və qovluqlar.",
    totalAmount: 120,
    status: "approved",
    category: "Ofis ləvazimatı",
    costCenter: "Kargüzarlıq",
    products: [{ id: "p3", name: "A4 kağız (top)", quantity: 10, value: 12 }],
    files: [],
  },
  {
    id: "4",
    prNo: "PR-0015",
    createdDate: "2024-03-04T11:45:00Z",
    requester: "Vüsal Rzayev",
    authorId: "user4",
    department: "Tikinti",
    description: "Generator üçün təcili ehtiyat hissələri.",
    totalAmount: 2100,
    status: "rejected",
    category: "Təsərrüfat",
    costCenter: "Baxım və Təmir",
    products: [{ id: "p4", name: "Yağ filtri", quantity: 2, value: 1050 }],
    files: [],
  },
  {
    id: "5",
    prNo: "PR-0016",
    createdDate: "2024-03-05T10:00:00Z",
    requester: "Turan Həsənov",
    authorId: "currentUser",
    department: "İT",
    description: "Səyahət üçün noutbuk çantası.",
    totalAmount: 85,
    status: "draft",
    category: "İT",
    costCenter: "İdarəetmə",
    products: [{ id: "p5", name: "Laptop Bag", quantity: 1, value: 85 }],
    files: [],
  },
];
