import type { IncomingRequest } from "./types";

export const mockIncomingRequests: IncomingRequest[] = [
  {
    id: "1",
    prNo: "PR-0012",
    requester: "Turan Həsənov",
    department: "İT",
    description: "Yeni proqram təminatı lisenziyaları və avadanlıqlar.",
    approvedDate: "2024-03-05T14:00:00Z",
    totalAmount: 1250,
    products: [
      {
        id: "p1",
        name: "Dell Monitor 27 inch",
        requestedQty: 2,
        inStockQty: 1,
        fulfilledQty: 0,
      },
    ],
    status: "pending",
  },
  {
    id: "2",
    prNo: "PR-0014",
    requester: "Aysel Quliyeva",
    department: "HR",
    description: "Yeni işçilər üçün ofis ləvazimatı - kağız və qovluqlar.",
    approvedDate: "2024-03-06T10:30:00Z",
    totalAmount: 120,
    products: [
      { id: "p3", name: "A4 kağız (top)", requestedQty: 10, inStockQty: 25, fulfilledQty: 0 },
      { id: "p6", name: "Plastik qovluq", requestedQty: 20, inStockQty: 50, fulfilledQty: 0 },
    ],
    status: "pending",
  },
  {
    id: "3",
    prNo: "PR-0018",
    requester: "Rəşad Məmmədov",
    department: "Tikinti",
    description: "Tikinti sahəsi üçün təhlükəsizlik avadanlıqları.",
    approvedDate: "2024-03-07T09:00:00Z",
    totalAmount: 780,
    products: [
      {
        id: "p7",
        name: "Təhlükəsizlik dəbilqəsi",
        requestedQty: 15,
        inStockQty: 8,
        fulfilledQty: 0,
      },
      {
        id: "p8",
        name: "Əlcək (cüt)",
        requestedQty: 30,
        inStockQty: 45,
        fulfilledQty: 0,
      },
      {
        id: "p9",
        name: "Reflektiv jilet",
        requestedQty: 10,
        inStockQty: 3,
        fulfilledQty: 0,
      },
    ],
    status: "pending",
  },
  {
    id: "4",
    prNo: "PR-0020",
    requester: "Nigar Əlizadə",
    department: "Maliyyə",
    description: "Maliyyə şöbəsi üçün printer kartuşları.",
    approvedDate: "2024-03-08T11:15:00Z",
    totalAmount: 340,
    products: [
      {
        id: "p10",
        name: "HP 26A Kartuş",
        requestedQty: 4,
        inStockQty: 6,
        fulfilledQty: 0,
      },
      {
        id: "p11",
        name: "HP 30A Kartuş",
        requestedQty: 2,
        inStockQty: 0,
        fulfilledQty: 0,
      },
    ],
    status: "pending",
  },
  {
    id: "5",
    prNo: "PR-0022",
    requester: "Elvin Hüseynov",
    department: "İT",
    description: "Server otağı üçün UPS batareyaları.",
    approvedDate: "2024-03-04T16:45:00Z",
    totalAmount: 2400,
    products: [
      {
        id: "p12",
        name: "APC UPS Batareya",
        requestedQty: 5,
        inStockQty: 2,
        fulfilledQty: 3,
      },
    ],
    status: "active",
    note: "Anbarda mövcud olan 3 ədəd verildi, qalan 2 ədəd üçün borcumuz qalır.",
  },
  {
    id: "6",
    prNo: "PR-0025",
    requester: "Səbinə Kazımova",
    department: "Təsərrüfat",
    description: "Ofis mətbəxi üçün gündəlik istehlak materialları.",
    approvedDate: "2024-03-09T08:30:00Z",
    totalAmount: 95,
    products: [
      {
        id: "p13",
        name: "Su dispenseri filtri",
        requestedQty: 2,
        inStockQty: 5,
        fulfilledQty: 2,
      },
      {
        id: "p14",
        name: "Plastik stəkan (paket)",
        requestedQty: 10,
        inStockQty: 12,
        fulfilledQty: 10,
      },
    ],
    status: "closed",
    note: "Bütün məhsullar tam təhvil verildi.",
  },
];

