// import type { PendingApprovalEntry } from "./types";

// export const PENDING_APPROVAL_MOCK_DATA: PendingApprovalEntry[] = [
//   {
//     id: 1,
//     operationType: "Mədaxil",
//     date: "2024-01-15",
//     source: "Kassa 1",
//     amount: 1500.5,
//     currency: "AZN",
//     destination: "Hesab 1",
//   },
//   {
//     id: 2,
//     operationType: "Məxaric",
//     date: "2024-01-16",
//     source: "Kassa 2",
//     amount: 750.25,
//     currency: "USD",
//     destination: "Hesab 2",
//   },
//   {
//     id: 3,
//     operationType: "Transfer",
//     date: "2024-01-17",
//     source: "Kassa 3",
//     amount: 2000.0,
//     currency: "EUR",
//     destination: "Hesab 3",
//   },
//   {
//     id: 4,
//     operationType: "Konvertasiya",
//     date: "2024-01-18",
//     source: "Kassa 1",
//     amount: 500.75,
//     currency: "AZN",
//     destination: "Hesab 4",
//   },
//   {
//     id: 5,
//     operationType: "Mədaxil",
//     date: "2024-01-19",
//     source: "Kassa 2",
//     amount: 3000.0,
//     currency: "USD",
//     destination: "Hesab 5",
//   },
//   {
//     id: 6,
//     operationType: "Məxaric",
//     date: "2024-01-20",
//     source: "Kassa 3",
//     amount: 1000.0,
//     currency: "EUR",
//     destination: "Hesab 6",
//   },
//   {
//     id: 7,
//     operationType: "Transfer",
//     date: "2024-01-21",
//     source: "Kassa 1",
//     amount: 1500.5,
//     currency: "AZN",
//     destination: "Hesab 7",
//   },
//   {
//     id: 8,
//     operationType: "Konvertasiya",
//     date: "2024-01-22",
//     source: "Kassa 2",
//     amount: 750.25,
//     currency: "USD",
//     destination: "Hesab 8",
//   },
//   {
//     id: 9,
//     operationType: "Mədaxil",
//     date: "2024-01-23",
//     source: "Kassa 3",
//     amount: 3000.0,
//     currency: "EUR",
//     destination: "Hesab 9",
//   },
//   {
//     id: 10,
//     operationType: "Məxaric",
//     date: "2024-01-24",
//     source: "Kassa 1",
//     amount: 1000.0,
//     currency: "AZN",
//     destination: "Hesab 10",
//   },
// ];