import {
  QuestionMarkCircleIcon,
  ShieldCheckIcon,
  UsersIcon,
  KeyIcon,
  ShieldExclamationIcon,
  Cog6ToothIcon,
  ListBulletIcon,
  HomeIcon,
  BanknotesIcon,
  UserGroupIcon,
  PlusIcon,
  Squares2X2Icon,
  AdjustmentsHorizontalIcon,
  CurrencyDollarIcon,
  CheckCircleIcon,
  ChartPieIcon,
  BuildingOfficeIcon,
  UserIcon,
  BriefcaseIcon,
  TableCellsIcon,
  ArchiveBoxIcon,
  ClipboardDocumentListIcon,
  Square3Stack3DIcon,
  CubeIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  GlobeAltIcon,
  MagnifyingGlassIcon,
  StarIcon,
  TrophyIcon,
  RectangleGroupIcon,
  BellIcon,
  DevicePhoneMobileIcon,
  XCircleIcon,
  ShoppingBagIcon,
  MegaphoneIcon,
  ClipboardDocumentCheckIcon,
  ShoppingCartIcon,
  DocumentDuplicateIcon,
  ArrowsRightLeftIcon,
  WrenchIcon,
  DocumentTextIcon as DocumentTextIconHero,
  InboxArrowDownIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleLeftEllipsisIcon,
} from "@heroicons/react/24/outline";
import { BsAward } from "react-icons/bs";
import type { HeroIcon, IconMapType } from "./types";

export const iconMap: IconMapType = {
  CRMIcon: RectangleGroupIcon,
  NotificationIcon: BellIcon,
  SecurityIcon: ShieldCheckIcon,
  SecurityUserIcon: UsersIcon,
  SecurityRoleIcon: KeyIcon,
  SecurityPermissionIcon: ShieldExclamationIcon,
  SettingsIcon: Cog6ToothIcon,
  EnumTypeIcon: ListBulletIcon,
  HomeIcon: HomeIcon,
  MoneyIcon: BanknotesIcon,
  UsersIcon: UserGroupIcon,
  PlusIcon: PlusIcon,
  ListIcon: Squares2X2Icon,
  CashIcon: CurrencyDollarIcon,
  CheckCircleIcon: CheckCircleIcon,
  PieChartIcon: ChartPieIcon,
  BuildingIcon: BuildingOfficeIcon,
  ActiveDirectoryIcon: AdjustmentsHorizontalIcon,
  UserIcon: UserIcon,
  SearchIcon: MagnifyingGlassIcon,
  BriefcaseIcon: BriefcaseIcon,
  TableIcon: TableCellsIcon,
  FileTextIcon: DocumentTextIconHero,
  DocumentTextIcon: DocumentTextIconHero,
  WarehouseIcon: CubeIcon,
  ArchiveBoxIcon: ArchiveBoxIcon,
  AssetsIcon: Square3Stack3DIcon,
  InventoryIcon: ClipboardDocumentListIcon,
  ClipboardDocumentListIcon: ClipboardDocumentListIcon,
  CalendarDaysIcon: CalendarDaysIcon,
  ChartBarIcon: ChartBarIcon,
  GlobeIcon: GlobeAltIcon,
  BadgeIcon: StarIcon,
  MedalIcon: TrophyIcon,
  StateAwardIcon: BsAward,
  TrophyIcon: TrophyIcon,
  ShoppingBagIcon: ShoppingBagIcon,
  MegaphoneIcon: MegaphoneIcon,
  ClipboardDocumentCheckIcon: ClipboardDocumentCheckIcon,
  ShoppingCartIcon: ShoppingCartIcon,
  DocumentDuplicateIcon: DocumentDuplicateIcon,
  ArrowsRightLeftIcon: ArrowsRightLeftIcon,
  WrenchIcon: WrenchIcon,
  InboxArrowDownIcon: InboxArrowDownIcon,
  ChatBubbleLeftRightIcon: ChatBubbleLeftRightIcon,
  ChatBubbleLeftEllipsisIcon: ChatBubbleLeftEllipsisIcon,
  DevicePhoneMobileIcon: DevicePhoneMobileIcon,
  XCircleIcon: XCircleIcon,
};

export const getIconComponent = (iconName?: string): HeroIcon => {
  return iconName && iconMap[iconName]
    ? iconMap[iconName]
    : QuestionMarkCircleIcon;
};
