import type { Warehouse } from "./types";

export const MOCK_WAREHOUSES: Warehouse[] = [
  {
    id: "1",
    name: "Mərkəzi Anbar",
    company: "Azera Doc MMC",
    type: "Central",
    location: "Bakı, Heydər Əliyev pr. 115",
    area: 2500,
    capacity: 10000,
    manager: "Əli Əliyev",
    status: "Active",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Sumqayıt Filialı",
    company: "Azera Doc MMC",
    type: "Distribution",
    location: "Sumqayıt, Sülh küç. 45",
    area: 1200,
    capacity: 5000,
    manager: "Vəli Vəliyev",
    status: "Active",
    createdAt: "2024-02-10",
  },
  {
    id: "3",
    name: "Gəncə Soyuq Anbar",
    company: "Azera Doc Gəncə",
    type: "ColdStorage",
    location: "Gəncə, Nizami küç. 12",
    area: 800,
    capacity: 3000,
    manager: "Həsən Həsənov",
    status: "Active",
    createdAt: "2024-03-05",
  },
  {
    id: "4",
    name: "Xırdalan Satış Nöqtəsi",
    company: "Azera Doc MMC",
    type: "Retail",
    location: "Xırdalan ş., Bakı-Sumqayıt şosesi",
    area: 300,
    capacity: 1000,
    manager: "Aysel Məmmədova",
    status: "Inactive",
    createdAt: "2024-03-20",
  },
];
